name: Get Vercel Preview URL

on:
  push:
    branches: [ main, master ]

jobs:
  get-vercel-preview:
    name: Fetch Vercel Preview URL
    runs-on: ubuntu-latest
    steps:
      - name: Get Vercel Preview URL
        id: vercel-preview
        uses: ViktorJT/Get-Vercel-preview-url@1.2.2
        with:
          vercel_access_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Display Preview URL
        run: |
          echo "Vercel Preview URL: ${{ steps.vercel-preview.outputs.preview_url }}"
          echo "Preview URL is ready: ${{ steps.vercel-preview.outputs.preview_url }}"
          
      - name: Create Summary
        if: always()
        run: |
          echo "## Vercel Preview URL Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Preview URL" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.vercel-preview.outputs.preview_url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Action Status" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.vercel-preview.outputs.preview_url }}" != "" ]; then
            echo "✅ Successfully retrieved Vercel preview URL" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Failed to retrieve Vercel preview URL" >> $GITHUB_STEP_SUMMARY
          fi 